### ISSUE TITLE
Website_Compress_html

### ISSUE THREAD

**Issue by LiberTang0** [blooparksystems/website#70]
I have an error when i create a database or open a database where website_compress_html is present in the addons folder:

```
2016-05-25 21:53:24,638 12552 INFO ooo werkzeug: 127.0.0.1 - - [25/May/2016 21:53:24] "GET /web HTTP/1.1" 500 -
2016-05-25 21:53:24,664 12552 ERROR ooo werkzeug: Error on request:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 194, in run_wsgi
    execute(self.server.app)
  File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 182, in execute
    application_iter = app(environ, start_response)
  File "C:\Users\Administrator\Desktop\odoo\openerp\service\server.py", line 291, in app
    return self.app(e, s)
  File "C:\Users\Administrator\Desktop\odoo\openerp\service\wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "C:\Users\Administrator\Desktop\odoo\openerp\service\wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "C:\Users\Administrator\Desktop\odoo\openerp\http.py", line 1293, in __call__
    return self.dispatch(environ, start_response)
  File "C:\Users\Administrator\Desktop\odoo\openerp\http.py", line 1267, in __call__
    return self.app(environ, start_wrapped)
  File "C:\Python27\lib\site-packages\werkzeug\wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "C:\Users\Administrator\Desktop\odoo\openerp\http.py", line 1445, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "C:\Users\Administrator\Desktop\odoo\openerp\http.py", line 1376, in get_response
    result = request.registry['ir.http']._handle_exception(e)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\base\ir\ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "C:\Users\Administrator\Desktop\odoo\openerp\http.py", line 669, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "C:\Users\Administrator\Desktop\odoo\openerp\http.py", line 1373, in get_response
    result.flatten()
  File "C:\Users\Administrator\Desktop\odoo\openerp\http.py", line 1244, in flatten
    self.response.append(self.render())
  File "C:\Users\Administrator\Desktop\odoo\openerp\http.py", line 1238, in render
    context=request.context)
  File "C:\Users\Administrator\Desktop\odoo\openerp\api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\base\ir\ir_ui_view.py", line 1022, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "C:\Users\Administrator\Desktop\odoo\openerp\api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\base\ir\ir_qweb.py", line 263, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\website_compress_html\ir\ir_qweb.py", line 81, in render_node
    qwebcontext)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\website_compress_html\ir\ir_qweb.py", line 106, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\website_compress_html\ir\ir_qweb.py", line 77, in render_node
    qwebcontext)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\base\ir\ir_qweb.py", line 438, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\website_compress_html\ir\ir_qweb.py", line 106, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\website_compress_html\ir\ir_qweb.py", line 77, in render_node
    qwebcontext)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\base\ir\ir_qweb.py", line 470, in render_tag_set
    qwebcontext[template_attributes["set"]] = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\website_compress_html\ir\ir_qweb.py", line 106, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\website_compress_html\ir\ir_qweb.py", line 77, in render_node
    qwebcontext)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\base\ir\ir_qweb.py", line 459, in render_tag_call_assets
    bundle = AssetsBundle(xmlid, cr=cr, uid=uid, context=context, registry=self.pool)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\base\ir\ir_qweb.py", line 1102, in __init__
    self.html = self.registry['ir.ui.view'].render(self.cr, self.uid, xmlid, context=context)
  File "C:\Users\Administrator\Desktop\odoo\openerp\api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\base\ir\ir_ui_view.py", line 1022, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "C:\Users\Administrator\Desktop\odoo\openerp\api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\base\ir\ir_qweb.py", line 263, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\website_compress_html\ir\ir_qweb.py", line 81, in render_node
    qwebcontext)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\website_compress_html\ir\ir_qweb.py", line 113, in render_element
    node=element, template=template)
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\website_compress_html\ir\ir_qweb.py", line 106, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "C:\Users\Administrator\Desktop\odoo\openerp\addons\website_compress_html\ir\ir_qweb.py", line 84, in render_node
    result += self.render_tail(element.tail, element, qwebcontext)
QWebException: 'ir.qweb' object has no attribute 'render_tail'
```

**Comment by christophlsa** [comment]
@LiberTang0 Which Odoo version do you use?

**Comment by LiberTang0** [comment]
V 8.0:

Metadata-Version: 1.1
Name: odoo
Version: 8.0-20160517
